Google: OK
zuul:
  ignored-headers:
  - Access-Control-Allow-Credentials
  - Access-Control-Allow-Origin
  sensitive-headers:
  - Cookie
  - Set-Cookie
  routes:
    Alice:
      path: /Alice/**
      url: https://alice-oc-service-vinaydighade-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/Alice
#      service-id: alice
#      strip-prefix: false